# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ad9f4a99239febc91ee51e303f902f35a9df8f4c8547b83ce799c5bb8a1d183a92064f7e033d790ab395ce4792ecddea24d6549459538ea17b027efa9872293

test:
  secret_key_base: 1e8d8f6d12199d955636641a8a9daff5e94e345970b1a7c51fd34bb260ad171afd30e1ff49c5c039d80bcf4a1326c7021179f331d79c856ee0eb32bcdda5222c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
